# Generated by Django 2.1.3 on 2018-11-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('depende_de', models.ForeignKey(blank=True, help_text='Cargo del cual depende directa o indirectamente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependientes', to='funcionarios.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='CargoRedSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=90)),
                ('url', models.URLField(blank=True, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='funcionarios.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=190)),
                ('apellidos', models.CharField(blank=True, max_length=190, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('cuit', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioEnCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_detectada', models.DateField(blank=True, null=True)),
                ('fecha_fin_detectada', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='funcionarios.Cargo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='funcionarios.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioRedSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=90)),
                ('url', models.URLField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='funcionarios.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
            ],
        ),
        migrations.AddField(
            model_name='funcionarioredsocial',
            name='red_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='funcionarios.RedSocial'),
        ),
        migrations.AddField(
            model_name='cargoredsocial',
            name='red_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='funcionarios.RedSocial'),
        ),
    ]
